# Generated by Django 2.2 on 2021-01-08 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_news_view'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='view',
            new_name='views',
        ),
    ]
